### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by Campillay-Israel** [undrbug/mercadoLiebre#1]
1. Elementos solicitados:

**Cumple**: Tiene todos los elementos solicitados.

2. Centrado del contenido, tamaño y márgenes:

**- Cumple:** Todo el contenido de los elementos está centrado.

**- Cumple:** Mantiene los requisitos de 2em para los iconos , el margen de 10px no es solo inferior, lo tiene en los 4 lados

3. Adaptabilidad a distintas pantallas:

**Cumple:** El sitio se adapta a distintas pantallas sin romperse.

4. Formulario de registro de usuario:

**Cumple:** El sitio cuenta con el formulario de registro de usuario.

5. Formulario de login:

**Cumple:** El sitio cuenta con el formulario de login.

6. Mensajes de error:

**Cumple:** Efectivamente se muestra el mensaje de error al ingresar información equivocada.

7. Barra de búsqueda:

**Cumple:** El search bar es un formulario.

8. Animaciones y transiciones:

**Cumple**: Se utilizan animaciones y propiedades de transición de CSS.

**9 .Cosas a destacar:**

Tiene buena estética y mucho cuidado en los detalles.

**10 .Cosas a mejorar:**

El posicionamiento de los productos en resolución desktop: aunque no rompe la estética porque quedan centrados, se vería más simétrico y mejor visualmente si todos los elementos mantienen un mismo tamaño.

**Comment by undrbug** [comment]
Corregido basandome en las correcciones y sugerencias. Se corrigio el margin-bottom: 20px y tomé la sugerencia aplicando un tamaño maximo para las cards.
