### ISSUE TITLE
Puntos a evaluar - Peer review

### ISSUE THREAD

**Issue by GabrielaBaldissone** [undrbug/mercadoLiebre#2]
- [x] 1 - ✅ - _Sugerencia:_ El logo de ML queda muy chico para desktop. 
- [x] 2 - ✅ - _Sugerencia:_ El copyright debía ir debajo a la izquierda de la pantalla. 
- [x] 3 - ⚠️ -  El nav no de despliega en las siguientes medidas  (imagen).  - _Sugerencia:_ En desktop se debían ver 4 productos, el tamaño de los mismos se ven muy grandes.
![Captura de pantalla 2024-07-02 204303](https://github.com/undrbug/mercadoLiebre/assets/113806247/6f5f6a05-98d6-4c9c-8832-9c2855377b08)
- [x] 4 - ✅ - _Sugerencia:_  El botón enviar me lleva a la siguiente página "Cannot POST /register". - Y el logo de ML, me lleva a "http://localhost:3000/"
- [x] 5 - ✅ - _Sugerencia:_  El botón enviar me lleva a lo siguiente (imagen). - Y el logo de ML, me lleva a "http://localhost:3000/"
![image](https://github.com/undrbug/mercadoLiebre/assets/113806247/2cdbee2c-02ed-413d-bc40-d2e1030f3e61)
- [x] 6 - ✅ - Solo validación HTML.
- [x] 7 - ✅ 
- [x] 8 - ✅ - Muy buenas, me gustan mucho. 
- [x] 9 - En general me gusta mucho la página, me gusta que el logo de ML me lleve a la página principal si es necesario, las animaciones estan bien hechas, son sutiles y al mismo tiempo se hacen notar. La idea de dar una bienvenida y un slogan estan acordes con el contenido.
- [x] 10 - Como sugerencia se podría mejorar los formularios, tanto de register como el login para una mejor apariencia, no tan vistosos, sino algo más sutil, más delicado.

**Comment by undrbug** [comment]
1 - Tomada la sugerencia del logo, aplicado y corregido.
2 - Yendo en contra del pedido del cliente, considero que el copyright queda mas estetico centrado. 
3 - Corregido el nav y mostrar 4 productos en la version desktop (1024px)
4 - submit corregido, cambie a GET ya que en el backend no tengo rutas para POST.
5 - Logo Linkeado al home (/).
10 - Aceptadas las sugerencias. Serán aplicadas!
